plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.4'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web:3.2.4'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.2.4'
    runtimeOnly 'com.mysql:mysql-connector-j:8.3.0'
    implementation 'io.github.amithkoujalgi:ollama4j:1.0.86'
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    developmentOnly 'org.springframework.boot:spring-boot-devtools:3.2.4'
    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.2.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'com.alphacephei:vosk:0.3.32'
    implementation 'net.java.dev.jna:jna:5.13.0'
}

tasks.named('test') {
    useJUnitPlatform()
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}